### ISSUE TITLE
Preroll ad should continue after visiting the offer URL

### ISSUE THREAD

**Issue by Shukuyen** [veeplay/ios-media-player#10]
When you return from the website linked in a preroll ad, the ad is skipped. It should however continue to play from the position where the user tapped on the ad.

**Comment by gabidobo** [comment]
You can use the `afterVideoAdTapped` property of a `APSVASTAdBreak` object - see http://veeplay.github.io/ios-media-player/Classes/APSVASTAdBreak.html#//api/name/afterVideoAdTapped and http://veeplay.github.io/ios-media-player/Constants/APSWebviewDismissedAction.html
