### ISSUE TITLE
Fix not played ads

### ISSUE THREAD

**Issue by woloda375** [veeplay/ios-media-player#11]
Hi

I tried your demo (on ios 9.3.1) and there was not successfully loaded any of ads. For example, try tap on Demo1 row and you will see green rectangle instead of ad. Or when you press demo2, you will not see anything ....

Thanks

**Comment by gabidobo** [comment]
Thank you for your feedback - we've released a new demo that you can get from https://itunes.apple.com/us/app/veeplay/id1139749494?mt=8.
