### ISSUE TITLE
Player controls in fullscreen do not respect iPhone X etc. safeAreaInsets

### ISSUE THREAD

**Issue by BerlinWheatley** [veeplay/ios-media-player#19]
When in fullscreen mode, the pause/play button is partly obscured by the curved corners in recent iPhone models.

![screenshot 2019-01-24 at 09 38 59](https://user-images.githubusercontent.com/45199427/51665529-4268fc00-1fbc-11e9-96cf-85df774e14fe.png)

**Comment by ov1d1u** [comment]
Closing this as it was fixed when we switched to Autolayout for controls.
