### ISSUE TITLE
APSVASTMediaBuilderPlugin causes crash

### ISSUE THREAD

**Issue by bernhard-eiling** [veeplay/ios-media-player#3]
We received a crash report related to APSVASTMediaBuilderPlugin.

Here is the crash report:

Incident Identifier: 6EC64427-53E1-4A9B-9B00-34A8E6B144D5
CrashReporter Key:   8198003E-8042-41B7-9F6A-8E876D5A6D48
Hardware Model:      iPhone7,2
Process:         wetter.com_a [207]
Path:            /var/mobile/Containers/Bundle/Application/46B09291-2299-4226-A931-85F1C2B7A71D/wetter.com_a.app/wetter.com_a
Identifier:      com.wetter.iosclient.alpha
Version:         0.1.0 (152)
Code Type:       ARM-64
Parent Process:  ??? [1]

Date/Time:       2015-10-03T11:13:38Z
Launch Time:     2015-10-03T11:13:01Z
OS Version:      iPhone OS 9.0.2 (13A452)
Report Version:  104

Exception Type:  SIGABRT
Exception Codes: #0 at 0x198c1b1e0
Crashed Thread:  0

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x15f5b15f0 of class APSVASTAdBreak was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x15f923b50> (
<NSKeyValueObservance 0x15f923cf0: Observer: 0x15df38530, Key path: state, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x15f923700>
)'

Last Exception Backtrace:
0   CoreFoundation                       0x00000001836dcf5c __exceptionPreprocess + 124
1   libobjc.A.dylib                      0x00000001982d3f80 objc_exception_throw + 52
2   CoreFoundation                       0x00000001836dcea4 +[NSException raise:format:] + 116
3   Foundation                           0x000000018459ab60 NSKVODeallocate + 296
4   CoreFoundation                       0x00000001835c8b20 -[__NSArrayM dealloc] + 148
5   wetter.com_a                         0x00000001001e9b2c -[APSVASTMediaBuilderPlugin .cxx_destruct] (APSVASTMediaBuilderPlugin.m:57)
6   libobjc.A.dylib                      0x00000001982d2b54 object_cxxDestructFromClass(objc_object*, objc_class*) + 144
7   libobjc.A.dylib                      0x00000001982de080 objc_destructInstance + 88
8   libobjc.A.dylib                      0x00000001982de0e0 object_dispose + 24
9   CoreFoundation                       0x00000001835c9ec4 -[__NSDictionaryM dealloc] + 148
10  CoreFoundation                       0x00000001835c9ec4 -[__NSDictionaryM dealloc] + 148
11  libobjc.A.dylib                      0x00000001982d2b54 object_cxxDestructFromClass(objc_object*, objc_class*) + 144
12  libobjc.A.dylib                      0x00000001982de080 objc_destructInstance + 88
13  libobjc.A.dylib                      0x00000001982de0e0 object_dispose + 24
14  wetter.com_a                         0x00000001001549f0 -[WCOMLivecamDetailViewController .cxx_destruct] (WCOMLivecamDetailViewController.m:32)
15  libobjc.A.dylib                      0x00000001982d2b54 object_cxxDestructFromClass(objc_object*, objc_class*) + 144
16  libobjc.A.dylib                      0x00000001982de080 objc_destructInstance + 88
17  libobjc.A.dylib                      0x00000001982de0e0 object_dispose + 24
18  UIKit                                0x0000000188fcf4f0 -[UIResponder dealloc] + 136
19  UIKit                                0x0000000188dc1414 -[UIViewController dealloc] + 1828
20  wetter.com_a                         0x0000000100110600 -[WCOMDetailViewController .cxx_destruct] (WCOMDetailViewController.m:25)
21  libobjc.A.dylib                      0x00000001982d2b54 object_cxxDestructFromClass(objc_object*, objc_class*) + 144
22  libobjc.A.dylib                      0x00000001982de080 objc_destructInstance + 88
23  libobjc.A.dylib                      0x00000001982de0e0 object_dispose + 24
24  UIKit                                0x0000000188fcf4f0 -[UIResponder dealloc] + 136
25  UIKit                                0x0000000188dc1414 -[UIViewController dealloc] + 1828
26  UIKit                                0x0000000188f83184 -[UIPresentationController .cxx_destruct] + 308
27  libobjc.A.dylib                      0x00000001982d2b54 object_cxxDestructFromClass(objc_object*, objc_class*) + 144
28  libobjc.A.dylib                      0x00000001982de080 objc_destructInstance + 88
29  libobjc.A.dylib                      0x00000001982de0e0 object_dispose + 24
30  UIKit                                0x0000000188f7f1d0 -[UIPresentationController dealloc] + 60
31  UIKit                                0x00000001894b4a00 -[_UIFullscreenPresentationController dealloc] + 60
32  UIKit                                0x0000000188f7ef64 __destroy_helper_block_411 + 20
33  libsystem_blocks.dylib               0x0000000198b298e8 _Block_release + 152
34  UIKit                                0x00000001895454ac -[_UIViewControllerTransitionContext .cxx_destruct] + 112
35  libobjc.A.dylib                      0x00000001982d2b54 object_cxxDestructFromClass(objc_object*, objc_class*) + 144
36  libobjc.A.dylib                      0x00000001982de080 objc_destructInstance + 88
37  libobjc.A.dylib                      0x00000001982de0e0 object_dispose + 24
38  UIKit                                0x0000000188d6031c -[_UIViewControllerTransitionContext dealloc] + 60
39  UIKit                                0x0000000188d602cc -[_UIViewControllerOneToOneTransitionContext dealloc] + 84
40  libsystem_blocks.dylib               0x0000000198b298e8 _Block_release + 152
41  UIKit                                0x0000000188f38f90 -[UIViewAnimationBlockDelegate .cxx_destruct] + 52
42  libobjc.A.dylib                      0x00000001982d2b54 object_cxxDestructFromClass(objc_object*, objc_class*) + 144
43  libobjc.A.dylib                      0x00000001982de080 objc_destructInstance + 88
44  libobjc.A.dylib                      0x00000001982de0e0 object_dispose + 24
45  CoreFoundation                       0x00000001835cc04c -[__NSDictionaryI dealloc] + 140
46  libobjc.A.dylib                      0x00000001982edae8 (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 504
47  CoreFoundation                       0x00000001835c0b6c _CFAutoreleasePoolPop + 24
48  CoreFoundation                       0x00000001836920c8 __CFRunLoopRun + 1632
49  CoreFoundation                       0x00000001835c0dc0 CFRunLoopRunSpecific + 380
50  GraphicsServices                     0x000000018e714088 GSEventRunModal + 176
51  UIKit                                0x0000000188c9af44 UIApplicationMain + 200
52  wetter.com_a                         0x000000010015fedc main (main.m:14)
53  libdyld.dylib                        0x0000000198afe8b8 start + 0

**Comment by ov1d1u** [comment]
Do you still encounter this issue? Can you send me the crash report to ovidiu@veeplay.com because it seems that something is missing from "Current observation info"

**Comment by Shukuyen** [comment]
This is still the most common crash in our app. You should have received log files via mail by @bernhard-eiling 
Let me know if you need more information.

**Comment by ov1d1u** [comment]
Can you tell me what happens in WCOMLivecamDetailViewController? What kind of ads are you showing (prerolls, midrolls or postrolls), maybe a JSON configuration example?

**Comment by gabidobo** [comment]
This should be fixed in the latest release of the SDK.
