### ISSUE TITLE
An AVPlayerItem cannot be associated with more than one instance of AVPlayer

### ISSUE THREAD

**Issue by brototyp** [veeplay/ios-media-player#5]
We rarely get the issue `*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'An AVPlayerItem cannot be associated with more than one instance of AVPlayer'`

Scince we only use the veeso player for video playback we strongly suspect it to cause this one.

I would love to provide a crash report but github requires me to have write permission to this repository. What would be the best way to get it to you?

**Comment by ov1d1u** [comment]
Hi,

You can send the crash report on ovidiu@veeplay.com

Regards,
Ovidiu

**Comment by brototyp** [comment]
Hi Ovidiu,

I just sent the E-Mail.

**Comment by gabidobo** [comment]
This should be solved in the latest version of the SDK.
