### ISSUE TITLE
Preroll stutters / jumps back to the beginning when playing

### ISSUE THREAD

**Issue by Shukuyen** [veeplay/ios-media-player#7]
Prerolls (maybe videos in general) are jumping back to the beginning once when they are played.
Also happens in other apps (like the one with the 7 in its name). 

See this video: https://www.dropbox.com/s/yiifvbr3i3c9b6c/Bug1740054_AdvertisingJumping_1.mp4?dl=0

**Comment by gabidobo** [comment]
Can you confirm that this issue is still happening on version 2.6.4 of the library? We need a scenario for replicating this.

**Comment by Shukuyen** [comment]
It looks like it's fixed in our dev version 👍
