### ISSUE TITLE
Player size is not adapting to multitasking

### ISSUE THREAD

**Issue by bernhard-eiling** [veeplay/ios-media-player#8]
Reproduction on iPad Air 2, iOS 9.0:

1. Player embedded, iPad Portrait, change multitasking size to 2:1
2. open fullscreen
3. rotate device by 180 or 360 degrees, this seems to be dependent by starting in regular portrait or upside down portrait
4. fullscreen size is as wide as the devices screen, 1/3 of the player is concealed by the other multitasking app

Step 2 and 3 can be applied interchanged and reproduce the same result.

**Comment by ov1d1u** [comment]
This should be fixed now
