### ISSUE TITLE
Returning from fullscreen to embedded player, Video rotates by 90 degrees

### ISSUE THREAD

**Issue by bernhard-eiling** [veeplay/ios-media-player#9]
Reproduction, iPad Air 2, iOS 9.0:

1. iPad Landscape, embedded
2. open fullscreen
3. close fullscreen
3. video image is animating by 90 degrees back to embedded mode
4. after the animation the image is aligned back correctly

**Comment by ov1d1u** [comment]
Fixed in (the upcoming) 2.1.3
